# name: &name "DefaultAsrConfig"

wandb:
    name: multitask_learning
    verbosity: 2
    exper_name: test_of_multitask_train_asr_kws
    save_dir: /mount/export3/multitask_asr_kws_logs/
asr:
    data_path: ./data
    train_url: train-clean-360
    test_url: test-clean
    device: cuda
    n_cnn_layers: 3
    n_rnn_layers: 5
    rnn_dim: 512
    n_class: 29
    n_feats: 128
    stride: 2
    dropout: 0.1
    learning_rate: 1e-3
    batch_size: 20
    epochs: 100
    log_step: 100
    save_dir: /mount/export3/multitask_asr_kws_logs/
    checkpont_path: /mount/export3/multitask_asr_kws_logs/models/test_of_asr_train/0511_205643/model_36_loss_0.365_wer_0.3462.pth

multitask:
    data_percent: 10
    learning_rate: 1e-4
    epochs: 100
    batch_size: 10
    val_batch_size: 50
    alpha_loss: 0.1
    log_step: 200
    checkpont_path: /mount/export3/multitask_asr_kws_logs/models/test_of_multitask_train_asr_kws/0605_202254/model_6_loss_0.334_wer_0.3347.pth
    kws:
        key_word: sheila
        kws_data_percent: 1.0
        train_test_split_percent: 0.8